import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter();

  const handleButtonClick = () => {
    router.push('projects')
  }

  return (
    <>
      <Head>
        <title>Aldrin Estrada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo1.png"/>
      </Head>
      <main className={styles.main}>
        <Image
          src={'/images/logo1.png'}
          height={400}
          width={400}
          alt={'main-logo'}
        />
        <h1>Hello, I'm Aldrin</h1>
        <button onClick={handleButtonClick}>Projects</button>
        <button>About Me</button>
        <button>Contact</button>
      </main>
    </>
  )
}
